---
# These tasks needs to update the same file
# Because multiple tasks are run in parellel, data can go missing
# We need to either run this in serial
# Or run this once only on one host with a look for all other hosts
# Because serial is messy, I'm doing the latter
# Thus, while this should be run against the kvmhost host, it will show one of your guests

- name: Update /etc/hosts to resolve new VMs
  blockinfile:
    path: /etc/hosts
    state: present
    marker: "# {mark} {{ hostvars[item]['inventory_hostname'] }} managed by virt_infra Ansible playbook"
    block: |-
      {{ hostvars[item]['vm_ip'] }} {{ hostvars[item]['inventory_hostname'] }}
  become: true
  delegate_to: "{{ groups['kvmhost'][0] }}"
  when:
    - hostvars[item]['vm_ip'] is defined and hostvars[item]['vm_ip']
    - hostvars[item]['virt_infra_state'] | default(virt_infra_state) == "running"
  with_items: "{{ play_hosts }}"
  run_once: true

- name: Add host to SSH config
  blockinfile:
    create: true
    mode: 0600
    state: present
    path: "{{ hostvars[groups['kvmhost'][0]].ansible_env.HOME }}/.ssh/config"
    marker: "# {mark} {{ hostvars[item]['inventory_hostname'] }} managed by virt_infra Ansible playbook"
    block: |-
      Host {{ hostvars[item]['vm_ip'] }} {{ hostvars[item]['inventory_hostname'] }}
        Hostname  {{ hostvars[item]['vm_ip'] }}
        User {{ hostvars[item]['virt_infra_user'] | default(hostvars[groups['kvmhost'][0]].ansible_env.USER) }}
      {% if hostvars[item]['virt_infra_ssh_keys'] is not defined %}
      {% if hostvars[groups['kvmhost'][0]].result_ssh_key_list.files is defined and hostvars[groups['kvmhost'][0]].result_ssh_key_list.files %}
      {% for file in hostvars[groups['kvmhost'][0]].result_ssh_key_list.files %}
      {{ "  IdentityFile " + file.path.split('.pub')[0] }}
      {% endfor %}
      {% elif hostvars[groups['kvmhost'][0]].result_ssh_key_gen.filename is defined and hostvars[groups['kvmhost'][0]].result_ssh_key_gen.filename %}
      {{ "  IdentityFile " + hostvars[groups['kvmhost'][0]].result_ssh_key_gen.filename.split('.pub')[0] }}
      {% endif %}
      {% endif %}
  become: false
  delegate_to: "{{ groups['kvmhost'][0] }}"
  when:
    - hostvars[item]['vm_ip'] is defined and hostvars[item]['vm_ip']
    - hostvars[item]['virt_infra_state'] | default(virt_infra_state) == "running"
  with_items: "{{ play_hosts }}"
  run_once: true
