---
- include_tasks: validations-initial.yml
- include_tasks: validations.yml
- include_tasks: defaults-get.yml
- include_tasks: virt-list.yml
- include_tasks: net-list.yml
- include_tasks: net-remove.yml
- include_tasks: net-create.yml
- include_tasks: defaults-set.yml
- include_tasks: pool-create.yml
- include_tasks: disk-create.yml
- include_tasks: virt-create.yml
- include_tasks: vbmc-create.yml
- include_tasks: net-list.yml
- include_tasks: virt-list.yml
- include_tasks: vbmc-list.yml
- include_tasks: virt-remove.yml
- include_tasks: disk-remove.yml
- include_tasks: vbmc-remove.yml
- include_tasks: hosts-add.yml
- include_tasks: hosts-remove.yml
- include_tasks: wait.yml

- name: Advise if SSH key was created
  debug:
    msg: item
  with_items:
    - SSH key created at {{ result_ssh_key_gen.filename }}
  when:
    - inventory_hostname in groups['kvmhost']
    - result_ssh_key_gen.filename is defined and result_ssh_key_gen.filename
